GET http://localhost:8081/avaliacoes HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5NmZhY2ViLTNiMTQtNDYyOC1hNDQ5LTllNTBlNGQ5MTY5YiIsIm5vbWVDb21wbGV0byI6IkpvaG4gTGVubm9uIiwiZW1haWwiOiJqb2huQHRlc3RlLmNvbSIsInRpcG8iOiJNIiwiaWF0IjoxNzAxOTg5ODgwLCJleHAiOjE3MDE5OTM0ODB9.7uNEkdSVa2cxuP9ENvS6smOo7PfI0_j0Tj_CXlM13Oo